---
- name: test playbook
  gather_facts: false
  hosts: localhost
  vars:
   backup: yes
   deploy: yes
  tasks:
    - name: set foo fact to an array
      set_fact: foo="[ 'one', 'two', 'three' ]"
    - debug: var=foo
    - name: add items to foo array fact
      set_fact: foo="{{foo}} + [ 'four' ]"
    - debug: var=foo[0]
    - name: perform conditions here
      file:
       path: /home/ec2-user/anil.txt
       state: touch 
      when: foo[0] == "one" 
    
    - name: perform testing here
      copy:
       src: /home/ec2-user/anil.txt
       dest: /home/ec2-user/ansible
      when: foo[1] == "two" 
