## anisble code deploy
---


- hosts: localhost 
  become_user: ec2-user
  become: yes
  tasks:
   - name: disable the disable_ela.sh cronjob first
     delegate_to: localhost
     script: /home/ec2-user/Reports/disablecron.sh
     register: anil
   - debug: msg="{{ anil.stdout  }}"
- hosts: localhost
  become: yes
  tasks:
   - name: shutdown tomcat servers on rcpylswwacs001,rcpylswwacs002
     command: sh /usr/local/tomcat9/bin/shutdown.sh
     register: result
   - debug: msg="{{ result.stdout }}"
   - name: Check if Apache is running
     shell: ps aux | grep -i tomcat |  awk '{print $2}'
     ignore_errors: yes
     changed_when: false
     register: service_apache_status
   - debug: msg="Check if Apache is running {{ service_apache_status }}"
   - debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}"
- hosts: localhost
  become: yes
  tasks:
   - name: rcpylsapacs001.mpfyieldstar.com as rms user to shutdown scheduler-web
     service:
      name: httpd
      state: stopped
   - name: check if scheduler-web running
     shell: ps aux | grep -i  httpd | awk '{print $2}'
     ignore_errors: yes
     changed_when: yes
     register: service_schedulerweb_status
   - debug: msg="Check if scheduler-web is running {{ service_schedulerweb_status }}"
   - debug: msg="service_apache_status.stdout != '' =  {{ service_schedulerweb_status.stdout != ''}}"


